<a href="https://colab.research.google.com/github/priya242/Data-Engineering/blob/main/DataIntegration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [135]:
df = pd.read_csv('/content/COVID_county_data.csv.gz')
df['county']=df['county']+' County'
df.head(10)

         date              county       state     fips  cases  deaths
0  2020-01-21    Snohomish County  Washington  53061.0      1     0.0
1  2020-01-22    Snohomish County  Washington  53061.0      1     0.0
2  2020-01-23    Snohomish County  Washington  53061.0      1     0.0
3  2020-01-24         Cook County    Illinois  17031.0      1     0.0
4  2020-01-24    Snohomish County  Washington  53061.0      1     0.0
5  2020-01-25       Orange County  California   6059.0      1     0.0
6  2020-01-25         Cook County    Illinois  17031.0      1     0.0
7  2020-01-25    Snohomish County  Washington  53061.0      1     0.0
8  2020-01-26     Maricopa County     Arizona   4013.0      1     0.0
9  2020-01-26  Los Angeles County  California   6037.0      1     0.0

In [53]:
df1 = pd.read_csv('/content/acs2017_census_tract_data.csv.gz')

In [45]:
#df1.columns
acs_data = df1[['State', 'County','TotalPop','Poverty','IncomePerCap']]
acs_data.head(10)
acs_data['Poverty(In Num)'] = (acs_data['TotalPop'] * acs_data['Poverty'])/ 100
acs_data['TotalIncome'] = (acs_data['TotalPop'] * acs_data['IncomePerCap'])
acs_data.head(10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

     State          County  ...  Poverty(In Num)  TotalIncome
0  Alabama  Autauga County  ...          197.415   60918210.0
1  Alabama  Autauga County  ...          486.528   41259312.0
2  Alabama  Autauga County  ...          497.595   71883860.0
3  Alabama  Autauga County  ...           98.141  119766156.0
4  Alabama  Autauga County  ...         1215.730  367758325.0
5  Alabama  Autauga County  ...          492.320   97877560.0
6  Alabama  Autauga County  ...          923.400   65075760.0
7  Alabama  Autauga County  ...          349.560  106706103.0
8  Alabama  Autauga County  ...         1665.951  301695793.0
9  Alabama  Autauga County  ...          579.698  164819242.0

[10 rows x 7 columns]

In [46]:
acs_data.drop(columns = ['Poverty', 'IncomePerCap'],inplace=True)
acs_data.head(5)

     State          County  ...  Poverty(In Num)  TotalIncome
0  Alabama  Autauga County  ...          197.415   60918210.0
1  Alabama  Autauga County  ...          486.528   41259312.0
2  Alabama  Autauga County  ...          497.595   71883860.0
3  Alabama  Autauga County  ...           98.141  119766156.0
4  Alabama  Autauga County  ...         1215.730  367758325.0

[5 rows x 7 columns]

In [165]:
acs_agg = acs_data.groupby(['State','County']).max()
acs_agg.head(5)

acs_agg['Poverty']= (acs_agg['Poverty(In Num)']/acs_agg['TotalPop'])*100
acs_agg['IncomePerCap']= acs_agg['TotalIncome']/acs_agg['TotalPop']

acs_agg.drop(columns = ['TotalIncome'],inplace=True)

acs_agg.head(5)

                        TotalPop    Poverty  IncomePerCap  Poverty(In Num)
State   County
Alabama Autauga County     11333  14.700000  32450.218389         1665.951
        Baldwin County     17748  10.904688  36329.000000         1935.364
        Barbour County      4291  29.538289  16556.845491         1267.488
        Bibb County         8704  18.309478  17425.265625         1593.657
        Blount County       9317  15.751529  26436.000000         1467.570

In [166]:
#Loudoun County Virginia, Washington County Oregon, Harlan County Kentucky, Malheur County Oregon

result = acs_agg.loc[[('Oregon', 'Washington County'),('Virginia','Loudoun County'),('Kentucky','Harlan County'),('Oregon','Malheur County')]]

result

                            TotalPop    Poverty  IncomePerCap  Poverty(In Num)
State    County
Oregon   Washington County     12595  17.998253  53974.000000         2266.880
Virginia Loudoun County        12791   6.383395  56732.000000          816.500
Kentucky Harlan County          4867  49.700000  15607.851449         2418.899
Oregon   Malheur County         5822  30.043988  15641.183786         1749.161

In [167]:
#TotalCases - total number of COVID cases for this county as of February 20, 2021
#Dec2020Cases - number of COVID cases recorded in this county in December of 2020
#df.columns.rename(['State', 'County'], inplace =True)
df.head(5)

df.rename(columns={"state": "State", "county": "County"},inplace=True)
covid_agg = df.groupby(['State','County']).max()
covid = covid_agg.rename(columns={"cases": "total cases", "deaths": "total deaths"})
covid.drop(columns = ['fips'],inplace=True)
result_covid = covid.loc[[('Oregon', 'Washington County'),('Virginia','Loudoun County'),('Kentucky','Harlan County'),('Oregon','Malheur County')]]
result_covid

                                  date  total cases  total deaths
State    County
Oregon   Washington County  2021-02-20        20866         209.0
Virginia Loudoun County     2021-02-20        22557         199.0
Kentucky Harlan County      2021-02-20         2352          68.0
Oregon   Malheur County     2021-02-20         3331          58.0

In [171]:
#TotalDeaths - total number of COVID deaths for this county as of February 20, 2021
#Dec2020Deaths - number of COVID deaths recorded in this county in December of 2020
covid_dec=df[(df['date'] > '2020-11-30') & (df['date'] < '2021-01-01')]
covid_dec.rename(columns={"cases": "dec_cases", "deaths": "dec_deaths"},inplace=True)
covid_dec_agg = covid_dec.groupby(['State','County']).max()
covid_dec_agg.drop(columns = ['fips'],inplace=True)
result_covid1 = covid_dec_agg.loc[[('Oregon', 'Washington County'),('Virginia','Loudoun County'),('Kentucky','Harlan County'),('Oregon','Malheur County')]]
result_covid1

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

                                  date  dec_cases  dec_deaths
State    County
Oregon   Washington County  2020-12-31      16070       142.0
Virginia Loudoun County     2020-12-31      14169       159.0
Kentucky Harlan County      2020-12-31       1538        18.0
Oregon   Malheur County     2020-12-31       2914        50.0

In [190]:
r = pd.concat([covid_dec_agg,covid], axis=1)
#result_covid2 = r.loc[[('Oregon')]]
result_covid3 = pd.concat([acs_agg,r], axis = 1)
final_result = result_covid3.loc[['Oregon']]
result_covid3=result_covid3.groupby(['State']).sum()
result_covid3

                           TotalPop      Poverty  ...  total cases  total deaths
State                                             ...
Alabama                    478376.0  1668.415002  ...     486001.0        9591.0
Alaska                     140121.0   431.870407  ...      57072.0         279.0
Arizona                    145910.0   483.554584  ...     807182.0       15492.0
Arkansas                   456339.0  1810.432207  ...     315623.0        5349.0
California                 642828.0  1404.193861  ...    3526851.0       49113.0
Colorado                   379304.0  1040.850484  ...     422519.0        5997.0
Connecticut                 70308.0   222.364246  ...     273308.0        7523.0
Delaware                    36141.0    66.183222  ...      84835.0        1367.0
District of Columbia         7853.0    46.886540  ...      39553.0         994.0
Florida                    818577.0  1466.921325  ...    1863699.0       29847.0
Georgia                   1201086.0  3991.725479  ...     959422.0       16246.0
Guam                            0.0     0.000000  ...       8685.0         131.0
Hawaii                      45733.0    84.601746  ...      27031.0         429.0
Idaho                      320735.0   751.658499  ...     169702.0        1829.0
Illinois                   641571.0  1943.429407  ...    1187837.0       22541.0
Indiana                    651089.0  1651.527572  ...     657851.0       12338.0
Iowa                       513415.0  1493.802721  ...     332229.0        5343.0
Kansas                     470111.0  1532.037669  ...     294071.0        4634.0
Kentucky                   725377.0  3016.612198  ...     400097.0        4592.0
Louisiana                  483608.0  1709.043004  ...     428908.0        9675.0
Maine                      105200.0   327.604162  ...      43393.0         661.0
Maryland                   201284.0   506.887328  ...     375953.0        7778.0
Massachusetts              114770.0   366.022208  ...     567764.0       15876.0
Michigan                   489137.0  1937.653343  ...     645051.0       16370.0
Minnesota                  499430.0  1410.701752  ...     478525.0        6493.0
Mississippi                544526.0  2396.542019  ...     290623.0        6559.0
Missouri                   670693.0  2488.378330  ...     512915.0        8153.0
Montana                    230900.0   939.467876  ...      98691.0        1346.0
Nebraska                   338405.0  1221.079710  ...     199771.0        2179.0
Nevada                     101464.0   268.882099  ...     291015.0        4884.0
New Hampshire               73338.0   181.433934  ...      73233.0        1153.0
New Jersey                 203345.0   402.580838  ...     768389.0       22926.0
New Mexico                 208898.0   855.831714  ...     182671.0        3618.0
New York                   498894.0  1440.964861  ...    1585692.0       47403.0
North Carolina             763556.0  2321.118507  ...     845518.0       10932.0
North Dakota               223592.0   637.715410  ...     101587.0        1481.0
Northern Mariana Islands        0.0     0.000000  ...        168.0           4.0
Ohio                       642947.0  1903.593704  ...     953663.0       16789.0
Oklahoma                   452717.0  1548.005763  ...     418775.0        4156.0
Oregon                     253583.0   772.468742  ...     152712.0        2159.0
Pennsylvania               501112.0  1364.053342  ...     916398.0       23617.0
Puerto Rico                523682.0  3931.714083  ...     132454.0        1957.0
Rhode Island                36313.0   117.594737  ...     128502.0        2523.0
South Carolina             391347.0  1187.628729  ...     501277.0        8259.0
South Dakota               261814.0  1219.386189  ...     111228.0        1867.0
Tennessee                  678436.0  2225.969391  ...     756302.0       11112.0
Texas                     1811791.0  4843.037125  ...    2596221.0       42203.0
Utah                       225780.0   461.393538  ...     366929.0        1856.0
Vermont                     75398.0   239.583888  ...      14376.0         212.0
Virgin Islands                  0.0     0.000000  ...       2617.0          32.0
Virginia                   901735.0  2509.110025  ...     562137.0        7327.0
Washington                 304474.0   859.678178  ...     337655.0        4890.0
West Virginia              306826.0  1166.728349  ...     129384.0        2257.0
Wisconsin                  451522.0  1277.641961  ...     616260.0        6891.0
Wyoming                    141018.0   293.054014  ...      53721.0         662.0

[55 rows x 8 columns]

In [195]:
R = final_result['total cases'].corr(final_result['Poverty'])
print(R)
final_result['CovidTotalCases'] = (final_result['total cases'] * 100000 / final_result['TotalPop'])
final_result
final_result['CovidDeathCases'] = (final_result['total deaths'] * 100000 / final_result['TotalPop'])
final_result
final_result['CovidDecTotalCases'] = (final_result['dec_cases'] * 100000 / final_result['TotalPop'])
final_result
final_result['CovidDecDeathCases'] = (final_result['dec_deaths'] * 100000 / final_result['TotalPop'])
final_result
# Entire USA result
U = result_covid3['total cases'].corr(result_covid3['Poverty'])
print(U)
result_covid3['CovidTotalCases'] = (result_covid3['total cases'] )

result_covid3['CovidDeathCases'] = (result_covid3['total deaths'] )

result_covid3['CovidDecTotalCases'] = (result_covid3['dec_cases'])

result_covid3['CovidDecDeathCases'] = (result_covid3['dec_deaths'])
result_covid3

0.3318299700396194
0.4595917890094481

                           TotalPop  ...  CovidDecDeathCases
State                                ...
Alabama                    478376.0  ...              4830.0
Alaska                     140121.0  ...               200.0
Arizona                    145910.0  ...              8879.0
Arkansas                   456339.0  ...              3676.0
California                 642828.0  ...             25965.0
Colorado                   379304.0  ...              4885.0
Connecticut                 70308.0  ...              5997.0
Delaware                    36141.0  ...               926.0
District of Columbia         7853.0  ...               786.0
Florida                    818577.0  ...             21675.0
Georgia                   1201086.0  ...             10594.0
Guam                            0.0  ...               123.0
Hawaii                      45733.0  ...               286.0
Idaho                      320735.0  ...              1439.0
Illinois                   641571.0  ...             17981.0
Indiana                    651089.0  ...              8263.0
Iowa                       513415.0  ...              3898.0
Kansas                     470111.0  ...              2778.0
Kentucky                   725377.0  ...              2963.0
Louisiana                  483608.0  ...              7489.0
Maine                      105200.0  ...               347.0
Maryland                   201284.0  ...              5915.0
Massachusetts              114770.0  ...             12423.0
Michigan                   489137.0  ...             13015.0
Minnesota                  499430.0  ...              5383.0
Mississippi                544526.0  ...              4787.0
Missouri                   670693.0  ...              5890.0
Montana                    230900.0  ...               965.0
Nebraska                   338405.0  ...              1694.0
Nevada                     101464.0  ...              3136.0
New Hampshire               73338.0  ...               760.0
New Jersey                 203345.0  ...             19042.0
New Mexico                 208898.0  ...              2479.0
New York                   498894.0  ...             37557.0
North Carolina             763556.0  ...              6819.0
North Dakota               223592.0  ...              1335.0
Northern Mariana Islands        0.0  ...                 2.0
Ohio                       642947.0  ...              8963.0
Oklahoma                   452717.0  ...              2489.0
Oregon                     253583.0  ...              1485.0
Pennsylvania               501112.0  ...             16020.0
Puerto Rico                523682.0  ...              1503.0
Rhode Island                36313.0  ...              1879.0
South Carolina             391347.0  ...              5296.0
South Dakota               261814.0  ...              1489.0
Tennessee                  678436.0  ...              6849.0
Texas                     1811791.0  ...             28156.0
Utah                       225780.0  ...              1273.0
Vermont                     75398.0  ...               136.0
Virgin Islands                  0.0  ...                23.0
Virginia                   901735.0  ...              5041.0
Washington                 304474.0  ...              3547.0
West Virginia              306826.0  ...              1338.0
Wisconsin                  451522.0  ...              5247.0
Wyoming                    141018.0  ...               438.0

[55 rows x 12 columns]

In [196]:
#COVID total cases vs. % population in poverty
R1 = result_covid3['CovidTotalCases'].corr(result_covid3['Poverty'])
print(R1)
#COVID total deaths vs. % population in poverty
R2 = result_covid3['CovidDeathCases'].corr(result_covid3['Poverty'])
print(R2)
#COVID total cases vs. Per Capita Income level
R3 = result_covid3['CovidTotalCases'].corr(result_covid3['IncomePerCap'])
print(R3)
#COVID total deaths vs. Per Capita Income level
R4 = result_covid3['CovidDeathCases'].corr(result_covid3['IncomePerCap'])
print(R4)
#COVID cases during December 2020 vs. % population in poverty
R5 = result_covid3['CovidDecTotalCases'].corr(result_covid3['Poverty'])
print(R5)
#COVID deaths during December 2020 vs. % population in poverty
R6 = result_covid3['CovidDecDeathCases'].corr(result_covid3['Poverty'])
print(R6)
#COVID cases during December 2020 vs. Per Capita Income level
R7 = result_covid3['CovidDecTotalCases'].corr(result_covid3['IncomePerCap'])
print(R7)
#COVID cases during December 2020 vs. Per Capita Income level
R8 = result_covid3['CovidDecDeathCases'].corr(result_covid3['IncomePerCap'])
print(R8)

0.4595917890094481
0.4039923589271534
0.5692700559700035
0.5135875358802434
0.4793948783903835
0.3825577526054134
0.5969305332512055
0.4985921311664938

In [197]:
#COVID total cases vs. % population in poverty
R1 = final_result['CovidTotalCases'].corr(final_result['Poverty'])
print(R1)
#COVID total deaths vs. % population in poverty
R2 = final_result['CovidDeathCases'].corr(final_result['Poverty'])
print(R2)
#COVID total cases vs. Per Capita Income level
R3 = final_result['CovidTotalCases'].corr(final_result['IncomePerCap'])
print(R3)
#COVID total deaths vs. Per Capita Income level
R4 = final_result['CovidDeathCases'].corr(final_result['IncomePerCap'])
print(R4)
#COVID cases during December 2020 vs. % population in poverty
R5 = final_result['CovidDecTotalCases'].corr(final_result['Poverty'])
print(R5)
#COVID deaths during December 2020 vs. % population in poverty
R6 = final_result['CovidDecDeathCases'].corr(final_result['Poverty'])
print(R6)
#COVID cases during December 2020 vs. Per Capita Income level
R7 = final_result['CovidDecTotalCases'].corr(final_result['IncomePerCap'])
print(R7)
#COVID cases during December 2020 vs. Per Capita Income level
R8 = final_result['CovidDecDeathCases'].corr(final_result['IncomePerCap'])
print(R8)

0.4107959010799331
0.39261885108213307
0.67217844804829
0.6045701150884264
0.3846509420347484
0.4074096277848708
0.664637225455696
0.5701599294577229